# Generated by Django 4.2 on 2023-07-19 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_Prediction_indicator_models_rules_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='error_cause',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
