# Generated by Django 4.2 on 2023-07-31 12:21
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_error_cause_size_upgrade'),
        ('api', '0008_LM_add_NAAlgorithmParameters_model'),
    ]

    operations = [
    ]
