# Generated by Django 4.2 on 2023-07-31 12:21
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_merge_20230731_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruleset',
            name='rules_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='naalgorithmparameters',
            unique_together={('algorithm_name', 'answer_string')},
        ),
    ]
