# Generated by Django 4.2 on 2023-08-02 08:03
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_Ruleset_rules_count_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='error_cause',
            field=models.TextField(default=''),
        ),
    ]
