# Generated by Django 4.2 on 2023-08-09 14:12
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_AG_add_CrossValidation_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetattributes',
            name='role',
            field=models.CharField(
                choices=[('attr', 'Attribute'), ('class', 'Classification')], default='attr'),
        ),
    ]
