# Generated by Django 4.2 on 2023-09-28 09:04
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_AG_Dataset_add_correlation_matrix_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crossvalidationresult',
            name='celery_task_id',
        ),
        migrations.RemoveField(
            model_name='ruleset',
            name='celery_task_id',
        ),
        migrations.RemoveField(
            model_name='task',
            name='celery_task_id',
        ),
        migrations.AddField(
            model_name='crossvalidationresult',
            name='celery_task',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.task'),
        ),
        migrations.AddField(
            model_name='ruleset',
            name='celery_task',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.task'),
        ),
    ]
