# Generated by Django 4.2 on 2023-10-10 14:54
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('api', '0026_AG_Task_model_simplify_and_change_relations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('report', models.TextField()),
                ('content_type', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.DeleteModel(
            name='DatasetReport',
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(
                fields=['content_type', 'object_id'], name='api_report_content_3b7a19_idx'),
        ),
    ]
