# Generated by Django 4.2 on 2023-11-02 14:38
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_LM_Rules_new_field_histogram'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='report',
        ),
        migrations.AddField(
            model_name='report',
            name='storage_path',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='error_cause',
            field=models.TextField(blank=True, default=''),
        ),
    ]
