# Generated by Django 4.2 on 2023-12-21 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0041_LM_new_model_Label"),
    ]

    operations = [
        migrations.AddField(
            model_name="rules",
            name="assigned_labels",
            field=models.ManyToManyField(to="api.label"),
        ),
    ]
