# Generated by Django 4.2 on 2024-03-07 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_AG_Task_add_id_within_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='title',
            field=models.CharField(max_length=75),
        ),
    ]
