# Generated by Django 4.2 on 2024-09-02 07:53
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_merge_20240913_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='payment_link',
            field=models.URLField(
                blank=True, max_length=1024, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
