# Generated by Django 4.2.16 on 2025-02-14 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0074_LM_new_model_RulesetImportAlgorithm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
