# Generated by Django 5.1.6 on 2025-04-03 07:40
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0077_CM_add_tours'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicatorMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('description_pl', models.TextField(blank=True, null=True)),
                ('type_of_problem', models.CharField(blank=True, choices=[('classification', 'Classification'), (
                    'regression', 'Regression'), ('survival', 'Survival')], db_index=True, default=None, max_length=20, null=True)),
                ('higher_is_better', models.BooleanField(default=True)),
            ],
            options={
                'unique_together': {('key', 'type_of_problem')},
            },
        ),
    ]
