import os

RULE_GENERATION_QUEUE_NAME = os.environ["CELERY_TASK_QUEUE_NAME"]
REPORT_GENERATION_QUEUE_NAME = os.environ["REPORT_TASK_QUEUE_NAME"]
CELERY_BROKER_URL = BROKER_URL = os.environ["CELERY_BROKER_URL"]
CELERY_TASK_DEFAULT_EXCHANGE = os.environ["CELERY_TASK_DEFAULT_EXCHANGE"]
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_TASK_QUEUES = {
    RULE_GENERATION_QUEUE_NAME: {
        "binding_key": os.environ["CELERY_TASK_QUEUE_KEY"],
    },
    REPORT_GENERATION_QUEUE_NAME: {
        "binding_key": os.environ["REPORT_TASK_QUEUE_KEY"],
    }
}
