"""
Django settings for rolap project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path

import ecs_logging
from corsheaders.defaults import default_headers
from rolap.settings.celery_config import *

# Build paths inside the project like this: BASE_DIR / 'subdir'.
SETTINGS_PATH = Path(__file__).resolve().parent
BASE_DIR = SETTINGS_PATH.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ['REST_API_SECRET_KEY']

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = [
    "127.0.0.1",
    "localhost",
    'rest-api'
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # third party
    'rest_framework',
    'corsheaders',
    # local
    'rolap.api',
    'keycloak_auth.apps.KeycloakAuthConfig',
    'django_injector',
    'rolap.stripe_payments',
]

AUTHENTICATION_BACKENDS = [
    'keycloak_auth.backend.KeycloakAuthBackend'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGIN_REGEXES = [
    'http://localhost:*',
]
CORS_ALLOW_HEADERS = (
    *default_headers,
    "responsetype",
)
CORS_EXPOSE_HEADERS = (
    "content-disposition",
)

ROOT_URLCONF = 'rolap.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'rolap.wsgi.application'

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Warsaw'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'keycloak_auth.backend.KeycloakAuthBackend',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'PAGE_SIZE': 20,
    'EXCEPTION_HANDLER': 'rolap.api.utils.exception_handler.custom_exception_handler'
}

KEYCLOAK = {
    'KEYCLOAK_URL': os.environ['KEYCLOAK_URL'],
    'REALM': os.environ['KEYCLOAK_REALM'],
    'CLIENT_ID': os.environ['KEYCLOAK_CLIENT_ID'],
    'CLIENT_SECRET': os.environ['KEYCLOAK_CLIENT_SECRET'],
    'ADMIN_USERNAME': os.environ['KEYCLOAK_ADMIN_USERNAME'],
    'ADMIN_PASSWORD': os.environ['KEYCLOAK_ADMIN_PASSWORD'],
}

STRIPE = {
    'STRIPE_PUBLIC_KEY': os.environ['STRIPE_TEST_PUBLIC'],
    'STRIPE_SECRET_KEY': os.environ['STRIPE_TEST_SECRET'],
    'STRIPE_WEBHOOK_SECRET': os.environ['STRIPE_WEBHOOK_SECRET'],
}

AUTH_USER_MODEL = "keycloak_auth.User"

STORAGE_CONFIG = {
    "user": os.environ["STORAGE_DB_USER"],
    "password": os.environ["STORAGE_DB_PASSWORD"],
    "db_name": os.environ["STORAGE_DB_NAME"],
    "host": os.environ["STORAGE_DB_HOST"],
    "port": os.environ["STORAGE_DB_PORT"],
}

RULES_EVALUATION_SERVICE = {
    'url': os.environ['RULES_EVALUATION_SERVICE_URL']
}

LOGS_DIR = os.path.join(BASE_DIR, 'logs')
os.makedirs(LOGS_DIR, exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'elasticsearch': {
            '()': ecs_logging.StdlibFormatter,
        },
    },
    'handlers': {
        'logger': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOGS_DIR, 'log.log'),
            'maxBytes': 15728640,  # 1024 * 1024 * 15B = 15MB
            'backupCount': 10,
            'formatter': 'elasticsearch',
        }
    },
    'loggers': {
        'rolap.api': {
            'handlers': ['logger'],
            'level': 'INFO',
            'propagate': True
        },
        'rolap.stripe_payments': {
            'handlers': ['logger'],
            'level': 'INFO',
            'propagate': True
        }
    }
}

MEDIA_URL = "/media/"

ROUND_DECIMAL_PLACES = int(os.environ["ROUND_DECIMAL_PLACES"])

VERSION_FILE_PATH: str = os.path.join(BASE_DIR, '..', '..', 'VERSION.txt')

DEFAULT_LIMITS = {
    "max_rows": int(os.environ.get("DATASET_MAX_ROWS", 10000)),
    "max_columns": int(os.environ.get("DATASET_MAX_COLUMNS", 50)),
    "max_size": int(os.environ.get("DATASET_MAX_SIZE_MB", 10)) * 1024 * 1024,
    "max_sum_size": int(os.environ.get("DATASET_MAX_SUM_SIZE_MB", 100)) * 1024 * 1024,
    "max_projects": int(os.environ.get("LIMIT_MAX_PROJECTS", 100)),
    "max_datasets": int(os.environ.get("LIMIT_MAX_DATASETS", 100)),
    "max_rulesets": int(os.environ.get("LIMIT_MAX_RULESETS", 100)),
    "max_reports": int(os.environ.get("LIMIT_MAX_REPORTS", 100)),
}

ALLOWED_CODECS = ["utf-8", "latin1", "cp1252", "ascii", "iso-8859-1"]

ALLOWED_DOWNLOAD_TYPES = ["csv", "xlsx"]

# Keycloak roles
KEYCLOAK_USER_ROLE = "rolap_user"
KEYCLOAK_OPERATOR_ROLE = "rolap_operator"
KEYCLOAK_WORKER_ROLE = "celery_worker"

# Reports SFTP server credentials
REPORTS_SFTP_HOST = os.environ["REPORTS_SFTP_HOST"]
REPORTS_SFTP_PORT = int(os.environ["REPORTS_SFTP_PORT"])
REPORTS_SFTP_USERNAME = os.environ["REPORTS_SFTP_USERNAME"]
REPORTS_SFTP_PASSWORD = os.environ["REPORTS_SFTP_PASSWORD"]

# Validation
ATTRIBUTES_REGEX = os.environ["ATTRIBUTES_REGEX"]
RULESET_NAME_REGEX = os.environ['RULESET_NAME_REGEX']

MAX_CLASSES = 100
