from abc import ABC
from abc import abstractmethod

import numpy as np
import Orange
import pandas as pd
import wittgenstein as lw
from emag_reports.discovery.indicators import calculate_regression_indicators
from emag_reports.preprocess import encode_dataset
from imodels import RuleFitRegressor
from Orange.data import ContinuousVariable
from Orange.data import DiscreteVariable
from Orange.data import Domain
from Orange.data import StringVariable
from Orange.data import Table
from Orange.data import TimeVariable
from pandas.api.types import is_categorical_dtype
from pandas.api.types import is_datetime64_any_dtype
from pandas.api.types import is_numeric_dtype
from pandas.api.types import is_object_dtype


def generate_rules_regression(df, target):
    """
    Generate rules using RuleFit algorithm.

    Args:
        df (pd.DataFrame): dataset
        target (str): target column
    """
    encoded_df, _, onehot_encoder, categorical_cols = encode_dataset(
        df, target, False)
    X = encoded_df.drop(target, axis=1)
    y = encoded_df[target]

    feature_names = X.columns.tolist()

    model = RuleFitRegressor()
    model.fit(X, y, feature_names=feature_names)
    y_pred = model.predict(X)
    print(model)
    calculate_regression_indicators(y, y_pred)


class Model(ABC):
    def __init__(self, params: str = None):
        """
        Class used as algorithm wrapper

        :param params: algorithm params
        """
        pass

    @abstractmethod
    def prepare_data(self, data):
        """
        Prepare data for algorithm

        :param data: data for prepare
        :return: X_train, X_test, y_train, y_test.
        """
        pass

    @abstractmethod
    def fit(self, X_train, y_train):
        """
        Fit model

        :param X_train: X_train data
        :param y_train: y_train data
        :return: model
        """
        pass

    @abstractmethod
    def predict(self, X):
        """
        Predict

        :param X: data
        :return: predictions
        """
        pass

    @abstractmethod
    def get_stats(self):
        """
        Get statistics about ruleset:"number_of_rules", "mean_rule_length", "condition_sum"

        :return: stats: dictonary
        """
        pass

    @abstractmethod
    def get_rules(self):
        """
        Get rules generated by model

        :return: list of rules
        """
        pass


class CN2Model(Model):
    def __init__(self, params) -> None:
        super().__init__(params)
        self.learner = Orange.classification.CN2Learner()

        self.learner.rule_finder.general_validator.min_covered_examples = params[
            "min_covered_examples"
        ]

        self.learner.rule_finder.general_validator.max_rule_length = params[
            "max_rule_length"
        ]

        self.learner.rule_finder.search_algorithm.beam_width = params[
            "beam_width"
        ]

    def prepare_data(self, train, test=None, class_name='class'):

        # put "class" columna at the end
        if test is not None:
            data = pd.concat([train, test])
        else:
            data = train
        class_col = data.pop(class_name)
        data.insert(len(data.columns), class_name, class_col)

        table = self._table_from_frame(
            data, class_name=class_name, force_nominal=True)
        if test is not None:
            table_train = table[train.index]
            test_indexes = [i for i in set(
                range(0, len(table))) - set(train.index)]
            table_test = table[test_indexes]

            X_train = table_train
            y_train = train[class_name]

            X_test = table_test
            y_test = test[class_name]

            return X_train, X_test, y_train, y_test
        else:
            X_train = table
            y_train = train[class_name]

            return X_train, y_train

    def fit(self, X_train, y_train):
        self.model = self.learner(X_train)

        return self.model

    def predict(self, X):

        probabilites = pd.DataFrame(
            self.model.predict(X.X), columns=self.model.domain.class_var.values
        )

        return probabilites.idxmax(axis=1)

    def get_stats(self):

        rules = self.get_rules()

        stats = dict()

        conditions_sum = 0
        for rule in rules:
            preimse, consequence = rule.split("THEN")
            conditions = preimse.split("AND")
            conditions_sum += len(conditions)

        stats["number_of_rules"] = len(rules)
        stats["mean_rule_length"] = conditions_sum / len(rules)
        stats["condition_sum"] = conditions_sum

        return stats

    def get_rules(self):
        rules = list()
        for rule in self.model.rule_list:
            rules.append(str(rule))

        return rules

    def _table_from_frame(self, df, class_name, *, force_nominal=False):
        """
        Convert pandas.DataFrame to Orange.data.Table

        Parameters
        ----------
        df : pandas.DataFrame
        force_nominal : boolean
            If True, interpret ALL string columns as nominal (DiscreteVariable).

        Returns
        -------
        Table
        """

        def _is_discrete(s):
            return (
                is_categorical_dtype(s)
                or is_object_dtype(s)
                and (force_nominal or s.nunique() < s.size ** 0.666)
            )

        def _is_datetime(s):
            if is_datetime64_any_dtype(s):
                return True
            try:
                if is_object_dtype(s):
                    pd.to_datetime(s, infer_datetime_format=True)
                    return True
            except Exception:  # pylint: disable=broad-except
                pass
            return False

        attrs, metas, calss_vars = [], [], []
        X, M = [], []

        # Iter over columns
        for name, s in df.items():
            name = str(name)
            if name == class_name:
                discrete = s.astype("category").cat
                calss_vars.append(
                    DiscreteVariable(
                        name, discrete.categories.astype(str).tolist())
                )
                X.append(discrete.codes.replace(-1, np.nan).values)
            elif _is_discrete(s):
                discrete = s.astype("category").cat
                attrs.append(
                    DiscreteVariable(
                        name, discrete.categories.astype(str).tolist())
                )
                X.append(discrete.codes.replace(-1, np.nan).values)
            elif _is_datetime(s):
                tvar = TimeVariable(name)
                attrs.append(tvar)
                s = pd.to_datetime(s, infer_datetime_format=True)
                X.append(s.astype("str").replace(
                    "NaT", np.nan).map(tvar.parse).values)
            elif is_numeric_dtype(s):
                attrs.append(ContinuousVariable(name))
                X.append(s.values)
            else:
                metas.append(StringVariable(name))
                M.append(s.values.astype(object))

        return Table.from_numpy(
            Domain(attrs, calss_vars, metas),
            np.column_stack(X) if X else np.empty((df.shape[0], 0)),
            None,
            np.column_stack(M) if M else None,
        )
