psql -U ${POSTGRES_USER} <<-END
    CREATE USER $STORAGE_DB_USER WITH PASSWORD '$STORAGE_DB_PASSWORD';
    CREATE DATABASE $STORAGE_DB_NAME OWNER $STORAGE_DB_USER;
    ALTER ROLE $STORAGE_DB_USER CREATEDB;
END
