psql -U ${POSTGRES_USER} <<-END
    CREATE USER $REST_API_DB_USER WITH PASSWORD '$REST_API_DB_PASSWORD';
    CREATE DATABASE $REST_API_DB_NAME OWNER $REST_API_DB_USER;
    ALTER ROLE $REST_API_DB_USER CREATEDB;
END
