server {
    listen 42;

    # frontend
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # prevent caching for assets files
    location /assets/ {
        root   /usr/share/nginx/html;
        # kill cache
        add_header Last-Modified $date_gmt;
        add_header Cache-Control 'no-store, no-cache';
        if_modified_since off;
        expires off;
        etag off;
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}

server {
    listen 80;

    # common settings
    proxy_set_header Host $http_host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Host $server_name;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_http_version 1.1;
    proxy_redirect off;

    # docs
    location /docs {
        proxy_pass http://rest-api:8000/docs;
    }
    # patch to make sure docs are available
    location /openapi.json {
        try_files /openapi.json /calculate/openapi.json;
    }

    # groups outside of /api
    location /admin {
        proxy_pass http://rest-api:8000/admin;
    }
    location /auth {
        proxy_pass http://rest-api:8000/auth;
    }
    location /manage {
        proxy_pass http://rest-api:8000/manage;
    }

    # rest-api - the instance for DB access
    location /api {
        proxy_pass http://rest-api:8000/api;
        client_max_body_size 100M;
        client_body_buffer_size 1024k;
        proxy_read_timeout 60;
    }

    # calc-rest-api - the instance for calculation
    location /calculate {
        proxy_pass http://calc-rest-api:8000/calculate;
        client_max_body_size 100M;
        client_body_buffer_size 1024k;
        proxy_read_timeout 600;
    }

    # bugs-reporting
    location /bugs/ {
        proxy_pass http://bug-reporting-service:8000/;
        client_max_body_size 100M;
        client_body_buffer_size 1024k;
        proxy_read_timeout 60;
    }
}
