# Generated by Django 4.2 on 2024-08-07 11:34
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_CM_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugreport',
            name='screenshot',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
