# Generated by Django 4.2 on 2023-07-11 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Algorithm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('problem_type', models.CharField(choices=[('classification', 'Classification'), ('regression', 'Regression'), ('survival', 'Survival')], max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('version', models.CharField(max_length=5)),
                ('description_pl', models.TextField()),
                ('description_en', models.TextField()),
            ],
            options={
                'unique_together': {('problem_type', 'name', 'version')},
            },
        ),
        migrations.CreateModel(
            name='AlgorithmParams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('parameter_type', models.CharField(choices=[('choice', 'choice'), ('int', 'int'), ('float', 'float'), ('bool', 'bool')], max_length=20)),
                ('description_pl', models.TextField()),
                ('description_en', models.TextField()),
                ('default_value', models.CharField(max_length=50)),
                ('min_value', models.CharField(max_length=50, null=True)),
                ('max_value', models.CharField(max_length=50, null=True)),
                ('algorithm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.algorithm')),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('storage_path', models.CharField(default='', max_length=200)),
                ('delimiter', models.CharField(default=';')),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('celery_task_id', models.UUIDField(null=True, unique=True)),
                ('create_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(max_length=100)),
                ('error_cause', models.CharField(default='', max_length=256)),
                ('type', models.CharField(max_length=100)),
                ('meta', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Ruleset',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_timestamp', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('generation_params', models.JSONField(default=dict)),
                ('ruleset', models.JSONField(default=dict)),
                ('avg_conditions_count', models.FloatField(null=True)),
                ('avg_precision', models.FloatField(null=True)),
                ('avg_coverage', models.FloatField(null=True)),
                ('celery_task_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('algorithm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.algorithm')),
                ('attached_to_dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attached_rulesets', to='api.dataset')),
                ('generated_from_dataset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generated_rulesets', to='api.dataset')),
            ],
        ),
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(null=True, unique=True)),
                ('p', models.IntegerField(null=True)),
                ('n', models.IntegerField(null=True)),
                ('P', models.IntegerField(null=True)),
                ('N', models.IntegerField(null=True)),
                ('indicators', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('ruleset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ruleset')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
                ('type_of_problem', models.CharField(choices=[('classification', 'Classification'), ('regression', 'Regression'), ('survival', 'Survival')], default='classification', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ParamsChoiceValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
                ('description_pl', models.TextField()),
                ('description_en', models.TextField()),
                ('algorithm_params', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.algorithmparams')),
            ],
        ),
        migrations.CreateModel(
            name='DatasetAttributes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('type', models.CharField(default='str')),
                ('role', models.CharField(default='attr')),
                ('min', models.FloatField(default=0)),
                ('max', models.FloatField(default=0)),
                ('average', models.FloatField(default=0)),
                ('missing_values_count', models.IntegerField()),
                ('mode', models.CharField(max_length=255, null=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='api.dataset')),
            ],
        ),
        migrations.AddField(
            model_name='dataset',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to='api.project'),
        ),
    ]
