# Generated by Django 4.2 on 2023-07-05 11:56
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="algorithm",
            unique_together={("problem_type", "name", "version")},
        ),
    ]
