# Generated by Django 4.2 on 2023-07-25 11:29
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_Prediction_indicator_models_rules_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetattributes',
            name='type',
            field=models.CharField(choices=[('str', 'string'), ('int', 'integer'), (
                'float', 'float'), ('bool', 'boolean')], default='str'),
        ),
        migrations.AddField(
            model_name='datasetattributes',
            name='unique_values',
            field=models.JSONField(null=True),
        ),
    ]
