# Generated by Django 4.2 on 2023-07-18 08:31
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_AG_DatasetAttributes_modify_type_field_and_add_unique_values"),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_number", models.IntegerField()),
                ("algorithm_name", models.CharField(max_length=100)),
                ("question_text_pl", models.TextField()),
                ("question_text_en", models.TextField()),
            ],
            options={
                "unique_together": {("algorithm_name", "question_number")},
            },
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer_number", models.IntegerField()),
                ("answer_text_pl", models.TextField()),
                ("answer_text_en", models.TextField()),
                (
                    "next_question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="api.question",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="question_answers",
                        to="api.question",
                    ),
                ),
            ],
        ),
    ]
