# Generated by Django 4.2 on 2023-07-18 09:09
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_LM_add_Question_and_Answer_models"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="answer",
            name="next_question",
        ),
        migrations.AddField(
            model_name="answer",
            name="next_question_number",
            field=models.IntegerField(null=True),
        ),
    ]
