# Generated by Django 4.2 on 2023-07-18 10:37
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_LM_Answer_model_change_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="NAAlgorithmParameters",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("algorithm_name", models.CharField(max_length=100)),
                ("answer_string", models.CharField(max_length=20)),
                ("params_json", models.JSONField()),
            ],
        ),
    ]
