# Generated by Django 4.2 on 2023-08-09 09:15
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_AG_Dataset_change_storage_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrossValidationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('num_folds', models.IntegerField()),
                ('result', models.JSONField(default=dict)),
                ('celery_task_id', models.UUIDField(editable=False)),
                ('ruleset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='cross_validation', to='api.ruleset')),
            ],
        ),
    ]
