# Generated by Django 4.2 on 2023-08-11 15:13
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_AG_add_DatasetAttribute_role_validation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruleset',
            name='algorithm',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.algorithm'),
        ),
    ]
