# Generated by Django 4.2 on 2023-08-22 09:30
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_AG_Ruleset_allow_null_algorithm'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithmparams',
            name='expert_induction',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='algorithmparams',
            name='algorithm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='algorithm_parameters', to='api.algorithm'),
        ),
        migrations.AlterField(
            model_name='algorithmparams',
            name='parameter_type',
            field=models.CharField(choices=[('choice', 'choice'), ('int', 'int'), (
                'float', 'float'), ('bool', 'bool'), ('input', 'input')], max_length=20),
        ),
        migrations.AlterField(
            model_name='algorithmparams',
            name='default_value',
            field=models.CharField(max_length=50, blank=True),
        ),
        migrations.AlterField(
            model_name='paramschoicevalues',
            name='algorithm_params',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice_values',
                                    to='api.algorithmparams'),
        ),
    ]
