# Generated by Django 4.2 on 2023-08-23 10:43
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_AG_AlgorithmParams_expert_induction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('STARTED', 'Started'), ('SUCCESS', 'Success'), (
                'FAILURE', 'Failure'), ('PENDING', 'Pending'), ('ABORTED', 'Aborted')], max_length=8),
        ),
    ]
