# Generated by Django 4.2 on 2023-08-25 14:00
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_AG_Task_status_enum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rules',
            name='uuid',
            field=models.UUIDField(null=True),
        ),
    ]
