# Generated by Django 4.2 on 2023-08-30 08:10
import django.utils.timezone
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_AG_Task_add_relation_to_project'),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="last_opened_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="project",
            name="updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
