# Generated by Django 4.2 on 2023-09-01 07:28
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_LM_Dataset_new_field_description'),
    ]

    operations = [
        migrations.AddField(
            model_name="rules",
            name="description",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
