# Generated by Django 4.2 on 2023-09-05 07:55
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0022_LM_Rules_new_field_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="rules",
            name="train_covered_y_median",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="rules",
            name="train_covered_y_std",
            field=models.FloatField(null=True),
        ),
    ]
