# Generated by Django 4.2 on 2023-09-12 11:12
import django.utils.timezone
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_LM_Rules_new_fields_traincovered'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.TextField(blank=True, null=True)),
                ('celery_task_id', models.UUIDField(null=True, unique=True)),
                ('create_timestamp', models.DateTimeField(
                    default=django.utils.timezone.now)),
                ('update_timestamp', models.DateTimeField(
                    default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), (
                    'STARTED', 'Started'), ('FAILURE', 'Failure'), ('DONE', 'Done')], max_length=8)),
                ('dataset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                 related_name='dataset_report', to='api.dataset')),
            ],
        ),
    ]
