# Generated by Django 4.2 on 2023-09-13 10:20
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0027_AG_change_Report_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="rules",
            name="histogram",
            field=models.JSONField(null=True),
        ),
    ]
