# Generated by Django 4.2 on 2023-11-14 11:25
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_AG_Dataset_add_name_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruleset',
            name='type',
            field=models.CharField(default='manual', max_length=16),
        ),
    ]
