# Generated by Django 4.2 on 2023-11-28 16:48
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_AG_Ruleset_add_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='type',
            field=models.CharField(choices=[(
                'EDA', 'EDA'), ('PREDICTION', 'PREDICTION')], default='EDA', max_length=16),
            preserve_default=False,
        ),
    ]
