# Generated by Django 4.2 on 2023-11-30 11:45
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_AG_Report_add_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='generation_params',
            field=models.JSONField(null=True),
        ),
    ]
