# Generated by Django 4.2 on 2023-11-30 16:18
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_AG_Report_add_params'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='type',
            field=models.CharField(choices=[(
                'EDA', 'EDA'), ('PREDICTION', 'PREDICTION'), ('WHITEBOX', 'WHITEBOX')], max_length=16),
        ),
    ]
