# Generated by Django 4.2 on 2023-12-06 08:31
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_AG_Report_add_new_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruleset',
            name='generation_time',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='ruleset',
            name='indicator_calculation_time',
            field=models.FloatField(null=True),
        ),
    ]
