# Generated by Django 4.2 on 2023-12-04 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0035_AG_Ruleset_add_timing_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="rules",
            name="kaplan_meier_estimator",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="datasetattributes",
            name="role",
            field=models.CharField(
                choices=[
                    ("attr", "Attribute"),
                    ("class", "Classification"),
                    ("survival_time", "Survival Time"),
                ],
                default="attr",
            ),
        ),
    ]
