# Generated by Django 4.2 on 2023-12-13 14:39
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_LM_model_Rules_new_field_for_survival'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='title',
            field=models.CharField(default='Report', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='algorithmparams',
            name='parameter_type',
            field=models.CharField(choices=[('choice', 'choice'), ('int', 'int'), ('float', 'float'), ('bool', 'bool'), ('input', 'input'), (
                'expert_rules', 'expert_rules'), ('expert_conditions', 'expert_conditions'), ('expert_attributes', 'expert_attributes')], max_length=20),
        ),
    ]
