# Generated by Django 4.2 on 2023-12-20 08:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0037_AG_Report_add_title"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="project",
            unique_together={("owner", "name")},
        ),
    ]
