# Generated by Django 4.2 on 2023-12-20 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0038_LM_model_Project_unique_name"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="ruleset",
            unique_together={("attached_to_dataset", "name")},
        ),
    ]
