# Generated by Django 4.2 on 2024-01-08 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0042_LM_Rule_new_field_assigned_labels"),
    ]

    operations = [
        migrations.AddField(
            model_name="ruleset",
            name="fraction_FDR_significant",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="ruleset",
            name="fraction_significant",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="ruleset",
            name="total_conditions_count",
            field=models.IntegerField(null=True),
        ),
    ]
