# Generated by Django 4.2 on 2024-01-30 14:35
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_LM_Dataset_new_field_class_distribution'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rules',
            old_name='train_covered_y_median',
            new_name='train_covered_y_mean',
        ),
    ]
