# Generated by Django 4.2 on 2024-01-31 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_CM_Rules_change_train_covered_median_to_train_covered_mean'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithmparams',
            name='parameter_name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='algorithmparams',
            name='parameter_name_pl',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
