# Generated by Django 4.2 on 2024-01-31 10:47
from django.db import migrations
from django.db import transaction
from rolap.api.models.datasets import DatasetReadParams


def calculate_class_distribution(df, target_attribute):
    return df[target_attribute].dropna().value_counts().to_dict()


@transaction.atomic
def update_class_distribution(apps, schema_editor):
    Dataset = apps.get_model('api', 'Dataset')
    classification_datasets = Dataset.objects.filter(
        project__type_of_problem="classification"
    )

    for dataset in classification_datasets:
        if dataset.class_distribution is None:
            target_attribute_obj = dataset.attributes.filter(
                role="class"
            ).first()

            if target_attribute_obj is None:
                print(f"Dataset {dataset.id} nie ma atrybutu klasyfikacji.")
                continue

            target_attribute = target_attribute_obj.name
            read_params = DatasetReadParams(
                limit=None, offset=None, sorting_column=None, asc=True,
                columns=[target_attribute], filters=None
            )

            df, _ = dataset.read_dataset_from_storage(read_params)

            class_distribution = calculate_class_distribution(
                df, target_attribute)
            dataset.class_distribution = class_distribution
            dataset.save()
            print(f"Zaktualizowano dataset {dataset.id}.")


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_LM_AlgorithmParams_new_fields_parameter_name'),
    ]

    operations = [
        migrations.RunPython(update_class_distribution),
    ]
