# Generated by Django 4.2 on 2024-01-29 15:41
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_update_class_distribution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rules',
            name='ruleset',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='api.ruleset'),
        ),
    ]
