# Generated by Django 4.2 on 2024-02-02 14:21
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('api', '0048_AG_Rules_change_related_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crossvalidationresult',
            name='celery_task',
        ),
        migrations.RemoveField(
            model_name='ruleset',
            name='celery_task',
        ),
        migrations.RemoveField(
            model_name='task',
            name='update_timestamp',
        ),
        migrations.AddField(
            model_name='task',
            name='finish_timestamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='result_content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='tasks_as_result', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='task',
            name='result_object_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='source_content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='tasks_as_source', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='task',
            name='source_object_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='start_timestamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=[
                               'source_content_type', 'source_object_id'], name='api_task_source__2339d1_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=[
                               'result_content_type', 'result_object_id'], name='api_task_result__9d98bb_idx'),
        ),
    ]
