# Generated by Django 4.2 on 2024-02-05 09:42

from django.db import migrations, models


def update_attribute_types(apps, schema_editor):
    DatasetAttributes = apps.get_model('api', 'DatasetAttributes')
    updated_count = 0
    skipped_count = 0

    for attribute in DatasetAttributes.objects.all():
        if attribute.type in ['float', 'int']:
            attribute.type = 'num'
            attribute.save()
            updated_count += 1
        elif attribute.type in ['str', 'bool']:
            attribute.type = 'cat'
            attribute.save()
            updated_count += 1
        else:
            print(
                f"Skipped updating DatasetAttribute with id {attribute.id} due to unrecognized type: {attribute.type}")
            skipped_count += 1

    print(
        f"Updated {updated_count} attributes. Skipped {skipped_count} attributes due to unrecognized types.")


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_AG_Task_add_related_objects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetattributes',
            name='type',
            field=models.CharField(
                choices=[('num', 'numerical'), ('cat', 'categorical')], default='cat'),
        ),

        migrations.RunPython(update_attribute_types),
    ]
