# Generated by Django 4.2 on 2024-02-15 10:49
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_AG_Dataset_add_default_0_values_of_rows_and_columns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limitgroup',
            name='max_columns',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='limitgroup',
            name='max_rows',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='limitgroup',
            name='max_size',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='limitgroup',
            name='max_sum_size',
            field=models.PositiveBigIntegerField(),
        ),
    ]
