# Generated by Django 4.2 on 2024-02-23 10:53
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_AG_LimitGroup_change_fields_to_bigint'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='inner_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
