# Generated by Django 4.2 on 2024-04-02 12:12
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_LM_Report_change_tittle_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='VotingMeasures',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('description_pl', models.TextField()),
                ('description_en', models.TextField()),
            ],
        ),
    ]
