# Generated by Django 4.2 on 2024-04-16 13:16
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_LM_new_model_VotingMeasures'),
    ]

    operations = [
        migrations.AddField(
            model_name='limitgroup',
            name='max_datasets',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='limitgroup',
            name='max_projects',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='limitgroup',
            name='max_reports',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='limitgroup',
            name='max_rulesets',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
