# Generated by Django 4.2 on 2024-05-07 12:33
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_AG_LimitGroup_add_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('STARTED', 'Started'), ('SUCCESS', 'Success'), ('FAILURE', 'Failure'), (
                'PENDING', 'Pending'), ('ABORTED', 'Aborted'), ('STOPPING', 'Stopping'), ('STOPPED', 'Stopped')], max_length=8),
        ),
    ]
