# Generated by Django 4.2 on 2024-07-30 13:40
from django.db import migrations


def clean_dangling_rules(apps, schema_editor):
    """Cleans dangling rules from the database.
    It means all the old rules are attached to a ruleset that are not used in the
    current version of this ruleset. Such rules may be present in the database due
    to the known bug described in ROLAP-1841. This migration aims to clean this mess
    and fix this issue.
    """
    Ruleset = apps.get_model('api', 'Ruleset')

    rulesets_count: int = 0
    dandling_rules_count: int = 0

    for ruleset in Ruleset.objects.all():
        dandling_rules = 0
        try:
            dandling_rules += _clean_dangling_ruleset_rules(apps, ruleset)
        except Exception as e:
            print(
                f'Failed to clean ruleset: pk={ruleset.pk} "{ruleset.name}" with error:\n {str(e)}')
        if dandling_rules > 0:
            print(
                f'Cleaned {dandling_rules_count} dangling rules from ruleset: pk={ruleset.pk} "{ruleset.name}"...'
            )
        dandling_rules_count += dandling_rules
        rulesets_count += 1
    print(
        f'Checked {rulesets_count} rulesets, ' +
        f'removed {dandling_rules_count} dangling rules.'
    )


def _clean_dangling_ruleset_rules(apps, ruleset) -> int:
    Rules = apps.get_model('api', 'Rules')

    ruleset_rules_count: int = ruleset.rules_count
    all_rules = Rules.objects \
        .filter(ruleset=ruleset) \
        .order_by('-created_at')
    dangling_rules = all_rules[ruleset_rules_count:]
    dandling_rules_count = dangling_rules.count()
    for rule in dangling_rules:
        rule.delete()
    return dandling_rules_count


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_LM_model_Dataset_new_field'),
    ]

    operations = [
        migrations.RunSQL('SET CONSTRAINTS ALL IMMEDIATE',
                          reverse_sql=migrations.RunSQL.noop),
        migrations.RunPython(clean_dangling_rules, atomic=True),
        migrations.AlterUniqueTogether(
            name='rules',
            unique_together={('ruleset', 'uuid')},
        ),
    ]
