# Generated by Django 4.2 on 2024-09-12 12:53
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_CM_change_default_prediction_strategy'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruleset',
            name='use_default_rule',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
