# Generated by Django 4.2 on 2024-09-13 08:31
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_AG_Ruleset_add_field_fraction_covered_examples'),
        ('api', '0065_CM_Ruleset_use_default_rule_field_added'),
    ]

    operations = [
    ]
