# Generated by Django 4.2 on 2024-09-16 10:39
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_LM_model_SubscriptionPlan_new_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruleset',
            name='voting_measure',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
