# Generated by Django 4.2.16 on 2025-01-09 10:40
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0070_LM_new_model_Subscription'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='naalgorithmparameters',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='naalgorithmparameters',
            name='algorithm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='na_algorithm_parameters', to='api.algorithm'),
        ),
        migrations.AddField(
            model_name='question',
            name='algorithm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='questions', to='api.algorithm'),
        ),
        migrations.AlterUniqueTogether(
            name='naalgorithmparameters',
            unique_together={('algorithm', 'answer_string')},
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('algorithm', 'question_number')},
        ),
        migrations.RemoveField(
            model_name='naalgorithmparameters',
            name='algorithm_name',
        ),
        migrations.RemoveField(
            model_name='question',
            name='algorithm_name',
        ),
        migrations.AlterField(
            model_name='algorithm',
            name='version',
            field=models.CharField(max_length=16),
        ),
    ]
