# Generated by Django 4.2.16 on 2025-01-09 10:40
from django.db import migrations


def multiply_algorithm_survey_objects(apps, _schema_editor):
    """
    This operation multiplies question, answer and non-advanced algorithm parameters objects
    for each algorithm in order to reflect the new structural relation between algorithms
    and the aforementioned objects.
    """
    Algorithm = apps.get_model('api', 'Algorithm')
    algorithms = Algorithm.objects.all()
    Question = apps.get_model('api', 'Question')
    original_questions = Question.objects.prefetch_related(
        'question_answers').all()
    original_answers = [question.question_answers.all()
                        for question in original_questions]
    NAAlgorithmParameters = apps.get_model('api', 'NAAlgorithmParameters')
    original_na_algorithm_parameters = NAAlgorithmParameters.objects.all()
    for algorithm in algorithms:
        for question, original_question_answers in zip(original_questions, original_answers):
            question.pk = None
            question.algorithm = algorithm
            question.save()
            for answer in original_question_answers:
                answer.pk = None
                answer.question = question
                answer.save()
        for naa_algorithm_parameter in original_na_algorithm_parameters:
            naa_algorithm_parameter.pk = None
            naa_algorithm_parameter.algorithm = algorithm
            if algorithm.problem_type == "survival":
                params_json = naa_algorithm_parameter.params_json
                params_json.pop("induction_measure", None)
                naa_algorithm_parameter.params_json = params_json
            naa_algorithm_parameter.save()
    Question.objects.filter(algorithm=None).delete()
    NAAlgorithmParameters.objects.filter(algorithm=None).delete()
    question_with_null_algorithm_count = Question.objects.filter(
        algorithm=None).count()
    naap_with_null_algorithm_count = NAAlgorithmParameters.objects.filter(
        algorithm=None).count()
    if question_with_null_algorithm_count > 0 or naap_with_null_algorithm_count > 0:
        raise Exception(
            "Some questions or NAAlgorithmParameters have not been assigned to any algorithm."
            "Next migration cannot be run."
        )


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0071_AG_add_Algorithm_as_FK_to_Questions_and_NAAP'),
    ]

    operations = [
        migrations.RunPython(multiply_algorithm_survey_objects),
    ]
