# Generated by Django 4.2.16 on 2025-01-09 11:34
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0072_AG_Algorithm_Question_NAAP_data_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='naalgorithmparameters',
            name='algorithm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='na_algorithm_parameters', to='api.algorithm'),
        ),
        migrations.AlterField(
            model_name='question',
            name='algorithm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='questions', to='api.algorithm'),
        ),
    ]
