# Generated by Django 4.2.16 on 2025-02-07 07:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0073_AG_Question_NAAP_add_not_null_constraint_to_algorithm_relation'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleSetImportAlgorithm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('implementation_url', models.URLField(blank=True, null=True)),
                ('description_pl', models.TextField(blank=True, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('supported_problem_types', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('classification', 'Classification'), ('regression', 'Regression'), ('survival', 'Survival')], max_length=20), default=list, size=None)),
            ],
        ),
    ]
