# Generated by Django 5.1.6 on 2025-03-14 13:47
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0075_LM_Subscription_field_subscription_id_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruleset',
            name='comments',
            field=models.JSONField(default=list, null=True),
        ),
    ]
