# Generated by Django 5.1.6 on 2025-04-11 10:01
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0078_CM_add_indicator_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithm',
            name='expert_induction',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='algorithm',
            name='na_generation',
            field=models.BooleanField(default=True),
        ),
    ]
