# Generated by Django 4.2 on 2023-08-08 07:06
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keycloak_auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bucket_id',
        ),
    ]
