# Generated by Django 4.2 on 2024-07-08 11:31
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('keycloak_auth', '0002_AG_User_remove_bucket_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(blank=True, choices=[(
                'pl', 'Polish'), ('en', 'English')], max_length=10, null=True),
        ),
    ]
