import { Injectable } from '@angular/core';

import { TranslateService } from '@ngx-translate/core';

import { Label } from '../../../common/components/label/interfaces/label.model';
import {
  Alignment,
  ButtonsName,
  ButtonsTemplate,
  CellTemplate,
  ColumnType,
  CustomizeColumnSettings,
  DataField,
  HeaderCellTemplate,
  Width,
} from './models/rules-customize-columns-api';

@Injectable({
  providedIn: 'root',
})
export class BaseCustomizeColumnsService {
  readonly defaultColumnsSettings: { [key in DataField]: CustomizeColumnSettings } = {
    [DataField.Active]: {
      alignment: Alignment.Center,
      allowEditing: true,
      allowFiltering: true,
      allowHiding: false,
      cellTemplate: CellTemplate.Active,
      headerCellTemplate: HeaderCellTemplate.Active,
      name: DataField.Active,
      type: ColumnType.Buttons,
      visible: true,
      visibleIndex: 3,
      width: Width.Small,
    },
    [DataField.String]: {
      alignment: Alignment.Left,
      allowFiltering: true,
      allowHiding: false,
      allowSorting: false,
      dataField: DataField.String,
      headerCellTemplate: HeaderCellTemplate.Translate,
      name: DataField.String,
      showInColumnChooser: false,
      visible: false,
      width: Width.Auto,
    },
    [DataField.Selectable]: {
      alignment: Alignment.Left,
      allowFiltering: true,
      allowHiding: false,
      allowSorting: false,
      dataField: DataField.Selectable,
      headerCellTemplate: HeaderCellTemplate.Translate,
      name: DataField.Selectable,
      showInColumnChooser: false,
      visible: false,
      width: Width.Auto,
    },
    [DataField.Premise]: {
      alignment: Alignment.Left,
      allowFiltering: true,
      allowHiding: false,
      allowSorting: false,
      headerCellTemplate: HeaderCellTemplate.Translate,
      name: DataField.Premise,
      showInColumnChooser: false,
      visible: false,
      width: Width.Auto,
      dataType: 'number',
    },
    [DataField.AutoIncrement]: {
      alignment: Alignment.Center,
      allowFiltering: false,
      allowHiding: false,
      allowSorting: true,
      cellTemplate: CellTemplate.AutoIncrement,
      headerCellTemplate: HeaderCellTemplate.Translate,
      name: DataField.AutoIncrement,
      visibleIndex: 0,
      visible: true,
      showInColumnChooser: true,
      width: Width.Auto,
      sortingMethod: (value1: string, value2: string) => this.autoIncrementSorting(value1, value2),
      dataType: 'number',
    },
    [DataField.RuleName]: {
      alignment: Alignment.Center,
      allowFiltering: false,
      allowHiding: false,
      allowSorting: true,
      visible: false,
      showInColumnChooser: false,
      cellTemplate: CellTemplate.RuleName,
      headerCellTemplate: HeaderCellTemplate.Translate,
      name: DataField.RuleName,
      visibleIndex: 0,
      width: Width.SmallMedium,
      calculateFilterExpression: (filterValue: string, selectedFilterOperation: string) => {
        const ruleNamePrefix: string = this.translate.instant('project.rules_coverage.rule_name_prefix');
        return [
          (rowData: Record<DataField, any>) => {
            if (!rowData?.autoIncrement) return '';
            return `${ruleNamePrefix}${rowData.autoIncrement}`;
          },
          selectedFilterOperation || 'contains',
          filterValue,
        ];
      },
    },
    [DataField.VisibleFilter]: {
      alignment: Alignment.Center,
      allowFiltering: true,
      allowHiding: false,
      allowEditing: true,
      cellTemplate: CellTemplate.VisibilityFilter,
      dataField: DataField.VisibleFilter,
      headerCellTemplate: HeaderCellTemplate.VisibilityFilter,
      name: DataField.VisibleFilter,
      showInColumnChooser: false,
      type: ColumnType.Buttons,
      visible: false,
      visibleIndex: 4,
      width: Width.Medium,
    },
    [DataField.Visible]: {
      alignment: Alignment.Center,
      allowFiltering: true,
      allowHiding: false,
      allowEditing: true,
      cellTemplate: CellTemplate.Visibility,
      dataField: DataField.Visible,
      headerCellTemplate: HeaderCellTemplate.Visibility,
      name: DataField.Visible,
      showInColumnChooser: false,
      type: ColumnType.Buttons,
      visible: false,
      visibleIndex: 5,
      width: Width.Medium,
    },

    [DataField.RuleUuid]: {
      alignment: Alignment.Left,
      allowFiltering: true,
      allowHiding: false,
      allowSorting: false,
      headerCellTemplate: HeaderCellTemplate.Translate,
      name: DataField.RuleUuid,
      showInColumnChooser: false,
      visible: false,
      width: Width.Auto,
    },
    [DataField.Uuid]: {
      alignment: Alignment.Center,
      allowFiltering: true,
      allowHiding: false,
      allowSorting: false,
      headerCellTemplate: HeaderCellTemplate.Translate,
      name: DataField.Uuid,
      visibleIndex: 1,
      width: Width.Auto,
      type: ColumnType.Buttons,
      buttons: [
        {
          name: ButtonsName.Edit,
          template: ButtonsTemplate.Edit,
        },
        {
          name: ButtonsName.Delete,
          template: ButtonsTemplate.Delete,
        },
      ],
    },
    [DataField.Labels]: {
      alignment: Alignment.Left,
      allowFiltering: true,
      allowHiding: false,
      allowSorting: true,
      cellTemplate: CellTemplate.Label,
      headerCellTemplate: HeaderCellTemplate.Translate,
      name: DataField.Labels,
      visibleIndex: 2,
      width: Width.Auto,
      visible: false,
      showInColumnChooser: false,
    },
    [DataField.LabelsText]: {
      alignment: Alignment.Left,
      allowFiltering: true,
      allowHiding: false,
      allowSorting: true,
      dataField: DataField.LabelsText,
      name: DataField.LabelsText,
      headerCellTemplate: HeaderCellTemplate.Label,
      cellTemplate: CellTemplate.Label,
      visibleIndex: 2,
      width: Width.Auto,
    },
    [DataField.Compare]: {
      alignment: Alignment.Center,
      allowEditing: true,
      allowFiltering: true,
      allowHiding: false,
      cellTemplate: CellTemplate.Compare,
      dataField: DataField.Compare,
      headerCellTemplate: HeaderCellTemplate.Compare,
      name: DataField.Compare,
      showInColumnChooser: false,
      type: ColumnType.Buttons,
      visible: false,
      visibleIndex: 3,
      width: Width.SmallMedium,
    },
    [DataField.DisplayString]: {
      alignment: Alignment.Left,
      allowFiltering: true,
      allowHiding: false,
      allowSorting: true,
      headerCellTemplate: HeaderCellTemplate.Translate,
      name: DataField.DisplayString,
      dataField: DataField.DisplayString,
      visibleIndex: 5,
      width: Width.Auto,
      minWidth: Width.Large,
    },
    [DataField.Conclusion]: {
      alignment: Alignment.Left,
      allowFiltering: true,
      allowHiding: false,
      allowSorting: true,
      headerCellTemplate: HeaderCellTemplate.Translate,
      name: DataField.Conclusion,
      visibleIndex: 6,
      width: Width.Auto,
      visible: false,
      showInColumnChooser: false,
    },

    /* This columns stores rule's conclusion in the original form consumable by API.
    This columns is needed only for classification rules where "conclusion" column
    stores only the string "value" field of the conclusion object. It is needed to fix
    the devexpress bug with sorting object columns. Although this column is redundant
    for other types of problem, for the sake of consistency it is kept the same for
    all of them problems.
    */
    [DataField.DisplayConclusion]: {
      alignment: Alignment.Left,
      allowFiltering: true,
      allowHiding: false,
      allowSorting: true,
      headerCellTemplate: HeaderCellTemplate.Translate,
      name: DataField.DisplayConclusion,
      visibleIndex: 6,
      width: Width.Auto,
    },
    [DataField.Precision]: {
      alignment: Alignment.Left,
      allowFiltering: true,
      allowHiding: true,
      allowSorting: true,
      name: DataField.Precision,
      visibleIndex: 7,
      width: Width.Small,
      headerCellTemplate: HeaderCellTemplate.Translate,
      dataType: 'number',
    },
    [DataField.Coverage]: {
      alignment: Alignment.Left,
      allowFiltering: true,
      allowHiding: true,
      allowSorting: true,
      visible: true,
      showInColumnChooser: true,
      name: DataField.Coverage,
      visibleIndex: 8,
      width: Width.Small,
      headerCellTemplate: HeaderCellTemplate.Translate,
      dataType: 'number',
    },
    [DataField.P]: {
      alignment: Alignment.Left,
      allowFiltering: true,
      allowHiding: true,
      allowSorting: true,
      name: DataField.P,
      visibleIndex: 100,
      width: Width.Auto,
      headerCellTemplate: HeaderCellTemplate.Translate,
      dataType: 'number',
    },
    [DataField.RuleIndex]: {
      alignment: Alignment.Left,
      allowFiltering: false,
      allowHiding: false,
      allowSorting: false,
      name: DataField.RuleIndex,
      visibleIndex: 100,
      width: Width.Auto,
    },

    //TODO: RN backend returns p_value or p-value depending on the project type
    //one backend fixes this, we should remove either pValue or pMinusValue
    [DataField.PValue]: {
      alignment: Alignment.Left,
      allowFiltering: true,
      allowHiding: true,
      allowSorting: true,
      name: DataField.PValue,
      visibleIndex: 100,
      width: Width.Auto,
      headerCellTemplate: HeaderCellTemplate.Translate,
      dataType: 'number',
    },
    [DataField.PMinusvalue]: {
      alignment: Alignment.Left,
      allowFiltering: true,
      allowHiding: true,
      allowSorting: true,
      name: DataField.PMinusvalue,
      visibleIndex: 100,
      width: Width.Auto,
      headerCellTemplate: HeaderCellTemplate.Translate,
      dataType: 'number',
    },
    [DataField.PUpperCase]: {
      alignment: Alignment.Left,
      allowFiltering: true,
      allowHiding: true,
      allowSorting: true,
      name: DataField.PUpperCase,
      visibleIndex: 100,
      width: Width.Auto,
      headerCellTemplate: HeaderCellTemplate.Translate,
      dataType: 'number',
    },
    [DataField.N]: {
      name: DataField.N,
      alignment: Alignment.Left,
      allowFiltering: true,
      allowHiding: true,
      allowSorting: true,
      visibleIndex: 100,
      width: Width.Auto,
      headerCellTemplate: HeaderCellTemplate.Translate,
      dataType: 'number',
    },
    [DataField.NUpperCase]: {
      alignment: Alignment.Left,
      allowFiltering: true,
      allowHiding: true,
      allowSorting: true,
      name: DataField.NUpperCase,
      visibleIndex: 100,
      width: Width.Auto,
      headerCellTemplate: HeaderCellTemplate.Translate,
      dataType: 'number',
    },

    [DataField.Sensitivity]: {
      alignment: Alignment.Left,
      allowFiltering: true,
      allowHiding: true,
      allowSorting: true,
      name: DataField.Sensitivity,
      visibleIndex: 100,
      width: Width.Auto,
      headerCellTemplate: HeaderCellTemplate.Translate,
      dataType: 'number',
    },

    [DataField.Specificity]: {
      alignment: Alignment.Left,
      allowFiltering: true,
      allowHiding: true,
      allowSorting: true,
      name: DataField.Specificity,
      visibleIndex: 100,
      width: Width.Auto,
      headerCellTemplate: HeaderCellTemplate.Translate,
      dataType: 'number',
    },
    [DataField.C2]: {
      alignment: Alignment.Left,
      allowFiltering: true,
      allowHiding: true,
      allowSorting: true,
      name: DataField.C2,
      visibleIndex: 100,
      width: Width.Auto,
      headerCellTemplate: HeaderCellTemplate.Translate,
      dataType: 'number',
    },
    [DataField.RelativeRisk]: {
      alignment: Alignment.Left,
      allowFiltering: true,
      allowHiding: true,
      allowSorting: true,
      name: DataField.RelativeRisk,
      visibleIndex: 100,
      width: Width.Auto,
      headerCellTemplate: HeaderCellTemplate.Translate,
      dataType: 'number',
    },

    [DataField.NegativePredictiveValue]: {
      alignment: Alignment.Left,
      allowFiltering: true,
      allowHiding: true,
      allowSorting: true,
      name: DataField.NegativePredictiveValue,
      visibleIndex: 100,
      width: Width.Auto,
      headerCellTemplate: HeaderCellTemplate.Translate,
      dataType: 'number',
    },
    [DataField.LRPlus]: {
      alignment: Alignment.Left,
      allowFiltering: true,
      allowHiding: true,
      allowSorting: true,
      name: DataField.LRPlus,
      visibleIndex: 100,
      width: Width.Auto,
      headerCellTemplate: HeaderCellTemplate.Translate,
      dataType: 'number',
    },
    [DataField.LRMinus]: {
      alignment: Alignment.Left,
      allowFiltering: true,
      allowHiding: true,
      allowSorting: true,
      name: DataField.LRMinus,
      visibleIndex: 100,
      width: Width.Auto,
      headerCellTemplate: HeaderCellTemplate.Translate,
      dataType: 'number',
    },

    [DataField.OddsRatio]: {
      alignment: Alignment.Left,
      allowFiltering: true,
      allowHiding: true,
      allowSorting: true,
      name: DataField.OddsRatio,
      visibleIndex: 100,
      width: Width.Auto,
      headerCellTemplate: HeaderCellTemplate.Translate,
      dataType: 'number',
    },

    [DataField.ShowCoverage]: {
      alignment: Alignment.Center,
      allowFiltering: true,
      allowHiding: true,
      allowSorting: true,
      name: DataField.ShowCoverage,
      visibleIndex: 100,
      width: Width.Small,
      headerCellTemplate: HeaderCellTemplate.Translate,
      dataType: 'number',
    },
    [DataField.FilterDataset]: {
      alignment: Alignment.Center,
      allowFiltering: true,
      allowHiding: true,
      allowSorting: true,
      name: DataField.FilterDataset,
      visibleIndex: 100,
      width: Width.Small,
      headerCellTemplate: HeaderCellTemplate.Translate,
    },
    [DataField.Correlation]: {
      alignment: Alignment.Left,
      allowFiltering: true,
      allowHiding: true,
      allowSorting: true,
      name: DataField.Correlation,
      visibleIndex: 100,
      width: Width.Auto,
      headerCellTemplate: HeaderCellTemplate.Translate,
      dataType: 'number',
    },
    [DataField.Lift]: {
      alignment: Alignment.Left,
      allowFiltering: true,
      allowHiding: true,
      allowSorting: true,
      name: DataField.Lift,
      visibleIndex: 100,
      width: Width.Auto,
      headerCellTemplate: HeaderCellTemplate.Translate,
      dataType: 'number',
    },

    [DataField.RSS]: {
      alignment: Alignment.Left,
      allowFiltering: true,
      allowHiding: true,
      allowSorting: true,
      name: DataField.RSS,
      visibleIndex: 100,
      width: Width.Auto,
      headerCellTemplate: HeaderCellTemplate.Translate,
      dataType: 'number',
    },
    [DataField.ConditionsCount]: {
      alignment: Alignment.Left,
      allowFiltering: true,
      allowHiding: true,
      allowSorting: true,
      name: DataField.ConditionsCount,
      visibleIndex: 100,
      width: Width.Auto,
      headerCellTemplate: HeaderCellTemplate.Translate,
      dataType: 'number',
    },
    [DataField.NUnique]: {
      alignment: Alignment.Left,
      allowFiltering: false,
      allowHiding: false,
      allowSorting: false,
      visible: false,
      showInColumnChooser: false,
      name: DataField.NUnique,
      visibleIndex: 100,
      width: Width.Auto,
      headerCellTemplate: HeaderCellTemplate.Translate,
      dataType: 'number',
    },
    [DataField.NumOfConditions]: {
      alignment: Alignment.Left,
      allowFiltering: true,
      allowHiding: true,
      allowSorting: true,
      name: DataField.NumOfConditions,
      visibleIndex: 100,
      width: Width.Auto,
      headerCellTemplate: HeaderCellTemplate.Translate,
      dataType: 'number',
    },
    [DataField.PValAdjusted]: {
      alignment: Alignment.Left,
      allowFiltering: true,
      allowHiding: true,
      allowSorting: true,
      name: DataField.PValAdjusted,
      visibleIndex: 100,
      width: Width.Auto,
      headerCellTemplate: HeaderCellTemplate.Translate,
      dataType: 'number',
    },

    [DataField.PUnique]: {
      alignment: Alignment.Left,
      allowFiltering: false,
      allowHiding: false,
      allowSorting: false,
      visible: false,
      showInColumnChooser: false,
      name: DataField.PUnique,
      visibleIndex: 100,
      width: Width.Auto,
      headerCellTemplate: HeaderCellTemplate.Translate,
      dataType: 'number',
    },
    [DataField.Name]: {
      alignment: Alignment.Left,
      allowFiltering: true,
      allowHiding: true,
      allowSorting: true,
      name: DataField.Name,
      visibleIndex: 100,
      width: Width.Auto,
      headerCellTemplate: HeaderCellTemplate.Translate,
    },
    [DataField.Key]: {
      alignment: Alignment.Left,
      allowFiltering: true,
      allowHiding: true,
      allowSorting: true,
      name: DataField.Key,
      visibleIndex: 100,
      width: Width.Auto,
      headerCellTemplate: HeaderCellTemplate.Translate,
    },
    [DataField.Value]: {
      alignment: Alignment.Left,
      allowFiltering: true,
      allowHiding: true,
      allowSorting: true,
      name: DataField.Value,
      visibleIndex: 100,
      width: Width.Auto,
      headerCellTemplate: HeaderCellTemplate.Translate,
    },
    [DataField.ConditionName]: {
      alignment: Alignment.Left,
      allowFiltering: true,
      allowHiding: true,
      allowSorting: true,
      name: DataField.ConditionName,
      visibleIndex: 100,
      width: Width.Auto,
      headerCellTemplate: HeaderCellTemplate.Translate,
    },

    [DataField.AttributeName]: {
      alignment: Alignment.Left,
      allowFiltering: true,
      allowHiding: true,
      allowSorting: true,
      name: DataField.AttributeName,
      visibleIndex: 100,
      width: Width.Auto,
      headerCellTemplate: HeaderCellTemplate.Translate,
    },
    [DataField.Bacc]: {
      alignment: Alignment.Left,
      allowFiltering: true,
      allowHiding: true,
      allowSorting: true,
      name: DataField.Bacc,
      visibleIndex: 100,
      width: Width.Auto,
      headerCellTemplate: HeaderCellTemplate.Translate,
      dataType: 'number',
    },
    [DataField.Importance]: {
      alignment: Alignment.Left,
      allowFiltering: true,
      allowHiding: true,
      allowSorting: true,
      name: DataField.Importance,
      visibleIndex: 100,
      width: Width.Auto,
      headerCellTemplate: HeaderCellTemplate.Translate,
      dataType: 'number',
    },
    [DataField.Condition]: {
      alignment: Alignment.Left,
      allowFiltering: true,
      allowHiding: true,
      allowSorting: true,
      name: DataField.Condition,
      visibleIndex: 100,
      width: Width.Auto,
      headerCellTemplate: HeaderCellTemplate.Translate,
      dataType: 'number',
    },
    [DataField.Recall]: {
      alignment: Alignment.Left,
      allowFiltering: true,
      allowHiding: true,
      allowSorting: true,
      name: DataField.Recall,
      visibleIndex: 100,
      width: Width.Auto,
      headerCellTemplate: HeaderCellTemplate.Translate,
      dataType: 'number',
    },
    [DataField.NumberOfRules]: {
      alignment: Alignment.Left,
      allowFiltering: true,
      allowHiding: true,
      allowSorting: true,
      name: DataField.NumberOfRules,
      visibleIndex: 100,
      width: Width.Auto,
      headerCellTemplate: HeaderCellTemplate.Translate,
      dataType: 'number',
    },
    [DataField.AverageNumberOfConditions]: {
      alignment: Alignment.Left,
      allowFiltering: true,
      allowHiding: true,
      allowSorting: true,
      name: DataField.AverageNumberOfConditions,
      visibleIndex: 100,
      width: Width.Auto,
      headerCellTemplate: HeaderCellTemplate.Translate,
      dataType: 'number',
    },
    [DataField.AveragePrecision]: {
      alignment: Alignment.Left,
      allowFiltering: true,
      allowHiding: true,
      allowSorting: true,
      visible: true,
      showInColumnChooser: true,
      name: DataField.AveragePrecision,
      visibleIndex: 100,
      width: Width.Auto,
      headerCellTemplate: HeaderCellTemplate.Translate,
      dataType: 'number',
    },
    [DataField.AverageCoverage]: {
      alignment: Alignment.Left,
      allowFiltering: true,
      allowHiding: true,
      allowSorting: true,
      name: DataField.AverageCoverage,
      visibleIndex: 100,
      width: Width.Auto,
      headerCellTemplate: HeaderCellTemplate.Translate,
      dataType: 'number',
    },
    [DataField.F1Macro]: {
      alignment: Alignment.Left,
      allowFiltering: true,
      allowHiding: true,
      allowSorting: true,
      name: DataField.F1Macro,
      visibleIndex: 100,
      width: Width.Auto,
      headerCellTemplate: HeaderCellTemplate.Translate,
      dataType: 'number',
    },
    [DataField.F1Micro]: {
      alignment: Alignment.Left,
      allowFiltering: true,
      allowHiding: true,
      allowSorting: true,
      name: DataField.F1Micro,
      visibleIndex: 100,
      width: Width.Auto,
      headerCellTemplate: HeaderCellTemplate.Translate,
      dataType: 'number',
    },
    [DataField.F1Weighted]: {
      alignment: Alignment.Left,
      allowFiltering: true,
      allowHiding: true,
      allowSorting: true,
      name: DataField.F1Weighted,
      visibleIndex: 100,
      width: Width.Auto,
      headerCellTemplate: HeaderCellTemplate.Translate,
      dataType: 'number',
    },
    [DataField.GMeanMacro]: {
      alignment: Alignment.Left,
      allowFiltering: true,
      allowHiding: true,
      allowSorting: true,
      name: DataField.GMeanMacro,
      visibleIndex: 100,
      width: Width.Auto,
      headerCellTemplate: HeaderCellTemplate.Translate,
      dataType: 'number',
    },
    [DataField.GMeanMicro]: {
      alignment: Alignment.Left,
      allowFiltering: true,
      allowHiding: true,
      allowSorting: true,
      name: DataField.GMeanMicro,
      visibleIndex: 100,
      width: Width.Auto,
      headerCellTemplate: HeaderCellTemplate.Translate,
      dataType: 'number',
    },
    [DataField.GMeanWeighted]: {
      alignment: Alignment.Left,
      allowFiltering: true,
      allowHiding: true,
      allowSorting: true,
      name: DataField.GMeanWeighted,
      visibleIndex: 100,
      width: Width.Auto,
      headerCellTemplate: HeaderCellTemplate.Translate,
      dataType: 'number',
    },
    [DataField.RecallMacro]: {
      alignment: Alignment.Left,
      allowFiltering: true,
      allowHiding: true,
      allowSorting: true,
      name: DataField.RecallMacro,
      visibleIndex: 100,
      width: Width.Auto,
      headerCellTemplate: HeaderCellTemplate.Translate,
      dataType: 'number',
    },
    [DataField.RecallMicro]: {
      alignment: Alignment.Left,
      allowFiltering: true,
      allowHiding: true,
      allowSorting: true,
      name: DataField.RecallMicro,
      visibleIndex: 100,
      width: Width.Auto,
      headerCellTemplate: HeaderCellTemplate.Translate,
      dataType: 'number',
    },
    [DataField.RecallWeighted]: {
      alignment: Alignment.Left,
      allowFiltering: true,
      allowHiding: true,
      allowSorting: true,
      name: DataField.RecallWeighted,
      visibleIndex: 100,
      width: Width.Auto,
      headerCellTemplate: HeaderCellTemplate.Translate,
      dataType: 'number',
    },

    [DataField.BalancedAccuracy]: {
      alignment: Alignment.Left,
      allowFiltering: true,
      allowHiding: true,
      allowSorting: true,
      name: DataField.BalancedAccuracy,
      visibleIndex: 100,
      width: Width.Auto,
      headerCellTemplate: HeaderCellTemplate.Translate,
      dataType: 'number',
    },
    [DataField.TP]: {
      alignment: Alignment.Left,
      allowFiltering: true,
      allowHiding: true,
      allowSorting: true,
      name: DataField.TP,
      visibleIndex: 100,
      width: Width.Auto,
      visible: false,
      showInColumnChooser: false,
      headerCellTemplate: HeaderCellTemplate.Translate,
      dataType: 'number',
    },
    [DataField.FP]: {
      alignment: Alignment.Left,
      allowFiltering: true,
      allowHiding: true,
      allowSorting: true,
      name: DataField.FP,
      visibleIndex: 100,
      visible: false,
      showInColumnChooser: false,
      width: Width.Auto,
      headerCellTemplate: HeaderCellTemplate.Translate,
      dataType: 'number',
    },

    [DataField.TN]: {
      alignment: Alignment.Left,
      allowFiltering: true,
      allowHiding: true,
      allowSorting: true,
      name: DataField.TN,
      visible: false,
      showInColumnChooser: false,
      visibleIndex: 100,
      width: Width.Auto,
      headerCellTemplate: HeaderCellTemplate.Translate,
      dataType: 'number',
    },

    [DataField.FN]: {
      alignment: Alignment.Left,
      allowFiltering: true,
      allowHiding: true,
      allowSorting: true,
      name: DataField.FN,
      visibleIndex: 100,
      visible: false,
      showInColumnChooser: false,
      width: Width.Auto,
      headerCellTemplate: HeaderCellTemplate.Translate,
      dataType: 'number',
    },
    [DataField.MCC]: {
      alignment: Alignment.Left,
      allowFiltering: true,
      allowHiding: true,
      allowSorting: true,
      name: DataField.MCC,
      visibleIndex: 100,
      width: Width.Auto,
      headerCellTemplate: HeaderCellTemplate.Translate,
      dataType: 'number',
    },
    [DataField.PPV]: {
      alignment: Alignment.Left,
      allowFiltering: true,
      allowHiding: true,
      allowSorting: true,
      name: DataField.PPV,
      visibleIndex: 100,
      width: Width.Auto,
      headerCellTemplate: HeaderCellTemplate.Translate,
      dataType: 'number',
    },

    [DataField.NPV]: {
      alignment: Alignment.Left,
      allowFiltering: true,
      allowHiding: true,
      allowSorting: true,
      name: DataField.NPV,
      visibleIndex: 100,
      width: Width.Auto,
      headerCellTemplate: HeaderCellTemplate.Translate,
      dataType: 'number',
    },

    [DataField.MAPE]: {
      alignment: Alignment.Left,
      allowFiltering: true,
      allowHiding: true,
      allowSorting: true,
      name: DataField.MAPE,
      visibleIndex: 100,
      width: Width.Auto,
      headerCellTemplate: HeaderCellTemplate.Translate,
      dataType: 'number',
    },

    [DataField.MAE]: {
      alignment: Alignment.Left,
      allowFiltering: true,
      allowHiding: true,
      allowSorting: true,
      name: DataField.MAE,
      visibleIndex: 10,
      width: Width.Auto,
      headerCellTemplate: HeaderCellTemplate.Translate,
      dataType: 'number',
    },
    [DataField.RMSE]: {
      alignment: Alignment.Left,
      allowFiltering: true,
      allowHiding: true,
      allowSorting: true,
      name: DataField.RMSE,
      visibleIndex: 11,
      width: Width.Auto,
      headerCellTemplate: HeaderCellTemplate.Translate,
      dataType: 'number',
    },

    [DataField.Support]: {
      alignment: Alignment.Left,
      allowFiltering: true,
      allowHiding: true,
      allowSorting: true,
      name: DataField.Support,
      visibleIndex: 100,
      width: Width.Auto,
      headerCellTemplate: HeaderCellTemplate.Translate,
      dataType: 'number',
    },

    [DataField.TotalConditionsCount]: {
      alignment: Alignment.Left,
      allowFiltering: true,
      allowHiding: true,
      allowSorting: true,
      name: DataField.TotalConditionsCount,
      visibleIndex: 100,
      width: Width.Auto,
      headerCellTemplate: HeaderCellTemplate.Translate,
      dataType: 'number',
    },

    [DataField.YCoveredMedian]: {
      alignment: Alignment.Left,
      allowFiltering: true,
      allowHiding: true,
      allowSorting: true,
      name: DataField.YCoveredMedian,
      visibleIndex: 100,
      width: Width.Auto,
      headerCellTemplate: HeaderCellTemplate.Translate,
      dataType: 'number',
    },

    [DataField.yCoveredAvg]: {
      alignment: Alignment.Left,
      allowFiltering: true,
      allowHiding: true,
      allowSorting: true,
      name: DataField.yCoveredAvg,
      visibleIndex: 100,
      width: Width.Auto,
      visible: false,
      headerCellTemplate: HeaderCellTemplate.Translate,
      dataType: 'number',
    },

    [DataField.yCoveredMax]: {
      alignment: Alignment.Left,
      allowFiltering: true,
      allowHiding: true,
      allowSorting: true,
      name: DataField.yCoveredMax,
      visibleIndex: 100,
      width: Width.Auto,
      visible: false,
      headerCellTemplate: HeaderCellTemplate.Translate,
      dataType: 'number',
    },

    [DataField.yCoveredMean]: {
      alignment: Alignment.Left,
      allowFiltering: true,
      allowHiding: true,
      allowSorting: true,
      name: DataField.yCoveredMean,
      visibleIndex: 100,
      width: Width.Auto,
      visible: false,
      headerCellTemplate: HeaderCellTemplate.Translate,
      dataType: 'number',
    },

    [DataField.yCoveredMin]: {
      alignment: Alignment.Left,
      allowFiltering: true,
      allowHiding: true,
      allowSorting: true,
      name: DataField.yCoveredMin,
      visibleIndex: 100,
      width: Width.Auto,
      visible: false,
      headerCellTemplate: HeaderCellTemplate.Translate,
      dataType: 'number',
    },

    [DataField.Logrank]: {
      alignment: Alignment.Left,
      allowFiltering: true,
      allowHiding: true,
      allowSorting: true,
      name: DataField.Logrank,
      visibleIndex: 11,
      width: Width.Auto,
      headerCellTemplate: HeaderCellTemplate.Translate,
      dataType: 'number',
    },

    [DataField.CensoredCount]: {
      alignment: Alignment.Left,
      allowFiltering: true,
      allowHiding: true,
      allowSorting: true,
      name: DataField.CensoredCount,
      visibleIndex: 100,
      width: Width.Auto,
      visible: false,
      headerCellTemplate: HeaderCellTemplate.Translate,
      dataType: 'number',
    },

    [DataField.MedianSurvivalTime]: {
      alignment: Alignment.Left,
      allowFiltering: true,
      allowHiding: true,
      allowSorting: true,
      name: DataField.MedianSurvivalTime,
      visibleIndex: 10,
      visible: true,
      width: Width.Auto,
      headerCellTemplate: HeaderCellTemplate.Translate,
      dataType: 'number',
    },

    [DataField.MedianSurvivalTimeCiLower]: {
      alignment: Alignment.Left,
      allowFiltering: true,
      allowHiding: true,
      allowSorting: true,
      name: DataField.MedianSurvivalTimeCiLower,
      visibleIndex: 100,
      width: Width.Auto,
      headerCellTemplate: HeaderCellTemplate.Translate,
      dataType: 'number',
    },

    [DataField.MedianSurvivalTimeCiUpper]: {
      alignment: Alignment.Left,
      allowFiltering: true,
      allowHiding: true,
      allowSorting: true,
      name: DataField.MedianSurvivalTimeCiUpper,
      visibleIndex: 100,
      width: Width.Auto,
      headerCellTemplate: HeaderCellTemplate.Translate,
      dataType: 'number',
    },

    [DataField.KaplanMeierEstimator]: {
      alignment: Alignment.Left,
      allowFiltering: false,
      allowHiding: false,
      allowSorting: false,
      name: DataField.KaplanMeierEstimator,
      visibleIndex: 9,
      width: Width.Auto,
      cellTemplate: CellTemplate.SurvivalRuleConclusionCurve,
      headerCellTemplate: HeaderCellTemplate.Translate,
      dataType: 'number',
    },

    [DataField.TrainCoveredYMax]: {
      alignment: Alignment.Left,
      allowFiltering: true,
      allowHiding: true,
      allowSorting: true,
      name: DataField.TrainCoveredYMax,
      visibleIndex: 100,
      width: Width.Auto,
      visible: false,
      headerCellTemplate: HeaderCellTemplate.Translate,
      dataType: 'number',
    },

    [DataField.TrainCoveredYMean]: {
      alignment: Alignment.Left,
      allowFiltering: true,
      allowHiding: true,
      allowSorting: true,
      name: DataField.TrainCoveredYMean,
      visibleIndex: 5,
      width: Width.Auto,
      visible: false,
      headerCellTemplate: HeaderCellTemplate.Translate,
      dataType: 'number',
    },

    [DataField.TrainCoveredYMin]: {
      alignment: Alignment.Left,
      allowFiltering: true,
      allowHiding: true,
      allowSorting: true,
      name: DataField.TrainCoveredYMin,
      visibleIndex: 100,
      width: Width.Auto,
      visible: false,
      headerCellTemplate: HeaderCellTemplate.Translate,
      dataType: 'number',
    },

    [DataField.TrainCoveredYStd]: {
      alignment: Alignment.Left,
      allowFiltering: true,
      allowHiding: true,
      allowSorting: true,
      name: DataField.TrainCoveredYStd,
      visibleIndex: 100,
      width: Width.Auto,
      visible: false,
      headerCellTemplate: HeaderCellTemplate.Translate,
      dataType: 'number',
    },

    [DataField.EventsCount]: {
      alignment: Alignment.Left,
      allowFiltering: true,
      allowHiding: true,
      allowSorting: true,
      name: DataField.EventsCount,
      visibleIndex: 100,
      width: Width.Auto,
      visible: false,
      headerCellTemplate: HeaderCellTemplate.Translate,
      dataType: 'number',
    },
    [DataField.CoveredCount]: {
      alignment: Alignment.Left,
      allowFiltering: true,
      allowHiding: true,
      allowSorting: true,
      name: DataField.CoveredCount,
      visibleIndex: 11,
      width: Width.Auto,
      headerCellTemplate: HeaderCellTemplate.Translate,
      dataType: 'number',
    },
    [DataField.LogRankStats]: {
      alignment: Alignment.Left,
      allowFiltering: false,
      allowHiding: true,
      allowSorting: false,
      name: DataField.LogRankStats,
      visibleIndex: 11,
      width: Width.Auto,
      headerCellTemplate: HeaderCellTemplate.Translate,
      dataType: 'number',
    },
  };

  /**
   * Sorting auto increment column.
   * In data source, this field is a string so it must be converted to a number to sort properly.
   *
   * @param value1 - current index
   * @param value2 - previous index
   */
  public autoIncrementSorting(value1: string, value2: string) {
    if (+value1 === +value2) return 0;
    if (+value1 < +value2) return -1;
    return 1;
  }

  /**
   * Customize the label column for proper xlxs and csv export.
   * Labels are saved as comma separated strings.
   *
   * @param cell - cell data
   */
  private customizeLabelColumn(cell: any): any {
    if (cell.target !== 'row') return; // do not customize filterRow
    if (!cell.value?.length) return '';

    return cell.value.map((x: Label) => x.name).join(', ');
  }

  constructor(public translate: TranslateService) {}
}
